#server
server:
  port: 8082
  tomcat:
    threads:
      max: 1000
      min-spare: 10
#spring
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pf?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  task:
    execution:
      pool:
        core-size: 10 #核心线程数，当池中线程数没达到core-size时，每来一个请求都创建一个新的线程
        queue-capacity: 256 #队列容量，当核心线程都在忙，再来新的任务，会将任务放到队列
        max-size: 128 #当核心线程都在忙，队列也满了，再来新的任务，此时会创建新的线程，直到达到maxSize
        keep-alive: 60 #当任务高峰过后，有些线程会空闲下来，这空闲现线程达到一定的时间会被释放。
        allow-core-thread-timeout: false
      thread-name-prefix: db-service-task-

mybatis:
  mapper-locations:
    - classpath:/mappers/*.xml
  type-aliases-package: com.zero.pojo

#mybatis-plus配置
mybatis-plus:
  #定义别名包  简化查询resultType配置
  type-aliases-package: com.zero.pojo
  #Mybatis的映射文件路径
  mapper-locations: classpath:/mappers/*.xml
  #开启驼峰映射    字段  属性 对应    去除字段中的"_"之后首字母大写
  configuration:
    map-underscore-to-camel-case: true
